config/application.yml, docs/02_lab_migrate/0203_application.yml, src/spring-petclinic-customers-service/src/main/java/org/springframework/samples/petclinic/customers/health/ServiceHealthIndicator.java
* Add sample to define custom probe with spring boot health incicator
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> feat: add sample to define health probe with spring-acutator

docs/03_lab_monitor/0303.md, infra/bicep/main.bicep, infra/bicep/main.parameters.json, infra/bicep/modules/database/mysql.bicep, infra/bicep/modules/network/private-dns-zone.bicep, infra/bicep/modules/shared/applicationInsights.bicep, infra/bicep/modules/shared/logAnalyticsWorkspace.bicep
* add AI
* add newOrExisting support for some external resource
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
=> add application insights create

docs/05_lab_openai/01.md, docs/05_lab_openai/02.md
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fix: fix style issue

docs/05_lab_openai/02.md, docs/08_lab_azd/0801.md, infra/bicep/main.bicep, infra/bicep/main.parameters.json, infra/bicep/modules/ai/openai.bicep, infra/bicep/modules/app/petclinic.bicep, src/spring-petclinic-chat-agent/src/main/resources/application.yml
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> feat: add bicep support for ai

infra/bicep/main.bicep, infra/bicep/main.parameters.json, infra/bicep/modules/ai/openai.bicep, infra/bicep/modules/app/petclinic.bicep, infra/bicep/modules/shared/resourceGroup.bicep, src/pom.xml
happy provision path for petclinic with open AI
```
[x] Yes
[ ] No
```
```
[ ] Bugfix
[x] Feature
```
=> happy path integration ok

docs/05_lab_openai/01.md, docs/05_lab_openai/02.md
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fix cli issue

config/application-passwordless.yml, infra/bicep/main.bicep, infra/bicep/main.parameters.json, infra/bicep/modules/ai/openai.bicep, infra/bicep/modules/app/petclinic.bicep, infra/bicep/modules/containerapps/containerapp.bicep
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> integrate for services, now services are running ok

LabTips.md
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fix: fix doc order

azure.yaml, docs/06_lab_automation/0601.md, docs/06_lab_automation/0602.md, infra/bicep/main.bicep, infra/bicep/modules/containerapps/containerapp-java-components.bicep
1. add springbootadmin binding to eureka
2. fix default placeholder image tag
3. refine the azd up steps
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[x] Feature
```
=> some minor improvements

config/chat-agent-passwordless.yml, docs/02_lab_migrate/0202.md, docs/03_lab_monitor/0303.md
1. version in script 3.0.2 to 3.2.5
2. add chat agent configurations
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
=> Fix minor issues on doc and config

docs/02_lab_migrate/0203_application.yml
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> add disabled jms config in lab 02 applicaiton.yml

docs/06_lab_automation/0601.md, docs/06_lab_automation/0603.md, docs/06_lab_automation/0604.md, infra/bicep/hooks/postprovision.sh
add some error case triage
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
=> improve scripts and add more docs

docs/02_lab_migrate/0201.md, docs/02_lab_migrate/0203.md, docs/02_lab_migrate/0205.md, docs/04_lab_secrets/04_openlab_secrets_aca.md, docs/06_lab_automation/06_openlab_automation.md, infra/bicep/main.bicep, infra/bicep/main.parameters.json
refine words about sql server password
and use default value for sql admin password in bicep parameters
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
=> refine the scenarios about mysql admin password

azure.yaml
use remote acr build instead of local docker build
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
=> use remote acr build for azd

.devcontainer/devcontainer.json, docs/06_lab_automation/0601.md, install.md, src/spring-petclinic-admin-server/Dockerfile, src/spring-petclinic-api-gateway/Dockerfile, src/spring-petclinic-chat-agent/Dockerfile, src/spring-petclinic-customers-service/Dockerfile, src/spring-petclinic-vets-service/Dockerfile, src/spring-petclinic-visits-service/Dockerfile
Add required components for dev container environment
Also:
1. fix: command in Dockerfile
2. doc: move prepare steps to Install page
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[x] Feature
```
=> Ready for dev-container environment

docs/07_lab_security/0704.md, infra/bicep/main.bicep, infra/bicep/modules/app/petclinic.bicep, infra/bicep/modules/containerapps/aca-environment.bicep, infra/bicep/modules/containerapps/containerapp-java-components.bicep, infra/bicep/modules/containerapps/containerapp.bicep, infra/bicep/modules/containerapps/serviceLiner.bicep
refactor and documents
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
=> refactor some bicep files

.github/workflows/azure-dev.yml, .github/workflows/maven-build.yml, .github/workflows/validation-sample-workflow.yml
add github action files
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
=> Configure Azure Developer Pipeline

.github/workflows/azure-dev.yml, .github/workflows/validation-sample-workflow.yml
use the latest version v0.2.2
see https://github.com/microsoft/template-validation-action
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
=> fix template-validation-action version

.github/workflows/azure-dev.yml
add environment to step `azd deploy`
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
=> add environment for 'azd deploy'

infra/bicep/main.bicep
put them in same group for better pipeline maintain
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
=> ACA environment infrastructure in same group

infra/bicep/main.bicep
Reverts Azure-Samples/java-microservices-aca-lab#93
=> Revert "ACA environment infrastructure in same group"

docs/06_lab_automation/0602.md, docs/06_lab_automation/0603.md, docs/06_lab_automation/0605.md, index.md
direct links in mark down file works for markdown, but not fit for github docs
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
=> fix the links in doc

infra/bicep/modules/ai/openai.bicep
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Fix: adjust model capacity to fasten response speed.

.github/workflows/validation-sample-workflow.yml, docs/06_lab_automation/0605.md
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> add explict options for validation pipeline, fix doc link

src/spring-petclinic-chat-agent/src/main/java/org/springframework/samples/petclinic/agent/chat/Agent.java, src/spring-petclinic-chat-agent/src/main/java/org/springframework/samples/petclinic/agent/chat/OwnerTools.java, src/spring-petclinic-chat-agent/src/main/java/org/springframework/samples/petclinic/agent/service/OwnerService.java, src/spring-petclinic-customers-service/src/main/java/org/springframework/samples/petclinic/customers/model/OwnerRepository.java, src/spring-petclinic-customers-service/src/main/java/org/springframework/samples/petclinic/customers/web/OwnerResource.java
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> update find by first name and update owner

index.md
bug fix
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
=> fix link in file index.md

.devcontainer/postCreateCommand.sh, azure.yaml, infra/bicep/hooks/predown.sh
Due to some limitation https://github.com/Azure/azure-dev/issues/4210, we need a flag to delete openai instance
auto set the flag for azd environment
azd config set alpha.deployment.stacks on
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
=> auto set azd config

.github/workflows/validation-sample-workflow.yml
to workaround a known issue
```
[ ] Yes
[x] No
```
```
[ x] Bugfix
[ ] Feature
```
=> revert microsoft/template-validation-action to 0.2.2

.github/workflows/validation-sample-workflow.yml
use template-validation-action@v0.3.2
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
=> use template-validation-action@v0.3.2

.github/workflows/validation-sample-workflow.yml, docs/02_lab_migrate/0201.md, docs/07_lab_security/0704.md, infra/bicep/main.bicep
add more track info
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
=> add some track info for telemetry data

infra/bicep/main.bicep
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
=> don't use reserved tag prefix

azure.yaml, infra/bicep/hooks/postprovision.ps1, infra/bicep/hooks/predown.ps1, infra/bicep/main.bicep
now we can run the lab in powershell
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
=> add hooks for windows powershell

src/spring-petclinic-customers-service/pom.xml, src/spring-petclinic-customers-service/src/main/resources/db/postgres/data.sql, src/spring-petclinic-customers-service/src/main/resources/db/postgres/schema.sql, src/spring-petclinic-vets-service/pom.xml, src/spring-petclinic-vets-service/src/main/resources/db/postgres/data.sql, src/spring-petclinic-vets-service/src/main/resources/db/postgres/schema.sql, src/spring-petclinic-visits-service/pom.xml, src/spring-petclinic-visits-service/src/main/resources/db/postgres/data.sql, src/spring-petclinic-visits-service/src/main/resources/db/postgres/schema.sql
This unit is by Spektra to add PostgreSQL binding for the sample app.
=> PostgreSQL binding for Spring-Petclinic-Microservices

infra/bicep/hooks/postprovision.ps1, infra/bicep/hooks/postprovision.sh, infra/bicep/main.bicep
for better user experience
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
=> azd output resource group link

.github/workflows/azure-dev.yml, .github/workflows/maven-build.yml, .github/workflows/pages.yml, .github/workflows/validation-sample-workflow.yml, .vscode/settings.json, Gemfile, cleanup.md, docker-compose.yml, docs/01_lab_plan/0105.md, docs/03_lab_monitor/0305.md, docs/06_lab_automation/0601.md, docs/06_lab_automation/0602.md, docs/06_lab_automation/0603.md, docs/06_lab_automation/0604.md, docs/06_lab_automation/0605.md, docs/06_lab_automation/06_openlab_automation.md, docs/07_lab_security/07_openlab_security_aca.md, docs/08_lab_private/08_openlab_private_endpoints_aca.md, docs/09_lab_messaging/09_openlab_messaging_aca.md, docs/10_lab_reliable_application/10_reliable_java_aca.md, docs/11_lab_scale/1101.md, docs/11_lab_scale/1102.md, docs/11_lab_scale/1103.md, docs/11_lab_scale/11_openlab_scale_aca.md, install.md, more.md, tips.md
workflow configurations
component versions
content list
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
=> Update some configurations to the github pages

azure.yaml, docs/02_lab_migrate/0202.md, docs/02_lab_migrate/0204.md, docs/02_lab_migrate/0205.md, docs/06_lab_automation/0601.md, infra/bicep/hooks/postprovision.ps1, infra/bicep/hooks/postprovision.sh, infra/bicep/hooks/preprovision.ps1, infra/bicep/hooks/preprovision.sh, infra/bicep/main.bicep, infra/bicep/modules/app/petclinic.bicep, infra/bicep/modules/containerapps/aca-environment.bicep
- remove admin server
- add role assignments for spring boot admin
- refine process
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
=> use spring boot admin instead of admin server; refine process

docs/10_lab_reliable_application/1001.md, docs/10_lab_reliable_application/1002.md, docs/10_lab_reliable_application/1003.md, docs/10_lab_reliable_application/10_reliable_java_aca.md, docs/11_lab_scale/11_openlab_scale_aca.md, infra/bicep/hooks/postprovision.ps1, infra/bicep/hooks/postprovision.sh, infra/bicep/hooks/preprovision.ps1, infra/bicep/hooks/preprovision.sh
- Refine the error messages on preprovision check to provide more information to the user
- docs, show reliable java section
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
=> refine the error messages on preprovision check

docs/01_lab_plan/0105.md, docs/02_lab_launch/0201.md, docs/02_lab_launch/0202.md, docs/03_lab_monitor/0305.md, docs/04_lab_secrets/0401.md, docs/04_lab_secrets/0402.md, docs/05_lab_openai/0501.md, docs/06_lab_automation/0601.md, docs/06_lab_automation/06_openlab_automation.md, docs/07_lab_security/0704.md, docs/08_lab_private/0801.md, docs/08_lab_private/0802.md, docs/09_lab_messaging/0902.md, docs/10_lab_reliable_application/1001.md, infra/bicep/hooks/postprovision.ps1, infra/bicep/hooks/postprovision.sh, install.md
documentation only
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
=> refine the processes on user object id

azure.yaml, docs/02_lab_launch/0201.md, docs/02_lab_launch/0202.md, docs/02_lab_launch/0203.md, docs/02_lab_launch/0203_application.yml, docs/02_lab_launch/0204.md, docs/02_lab_launch/0205.md, docs/02_lab_launch/0206.md, docs/03_lab_monitor/0303.md, docs/03_lab_monitor/0305.md, docs/06_lab_automation/0601.md, docs/06_lab_automation/06_openlab_automation.md, docs/10_lab_reliable_application/10_reliable_java_aca.md, index.md, install.md, more.md, src/spring-petclinic-admin-server/Dockerfile, src/spring-petclinic-admin-server/ai.Dockerfile, src/spring-petclinic-api-gateway/ai.Dockerfile, src/spring-petclinic-chat-agent/Dockerfile, src/spring-petclinic-chat-agent/ai.Dockerfile, src/spring-petclinic-customers-service/Dockerfile, src/spring-petclinic-customers-service/ai.Dockerfile, src/spring-petclinic-messaging-emulator/Dockerfile, src/spring-petclinic-messaging-emulator/ai.Dockerfile, src/spring-petclinic-vets-service/Dockerfile, src/spring-petclinic-vets-service/ai.Dockerfile, src/spring-petclinic-visits-service/Dockerfile, src/spring-petclinic-visits-service/ai.Dockerfile
And some process refine
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
=> use acr to build images remotely

docs/03_lab_monitor/03_openlab_monitoring_aca.md, docs/04_lab_secrets/0403.md, docs/10_lab_reliable_application/1001.md, docs/10_lab_reliable_application/1002.md, docs/10_lab_reliable_application/1003.md
fix
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
=> fix the parent page for lab reliabe java

.github/workflows/validation-sample-workflow.yml, infra/bicep/hooks/postprovision.sh, infra/bicep/hooks/preprovision.sh
This is a workaround for pipeline check
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
=> disable AAD user operations on dev container environment

docs/04_lab_secrets/0403.md, tools/update-apps-passwordless.sh
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
=> minor fix on commands

docs/05_lab_openai/05_openai.md, docs/05_lab_openai/05_openai_existing.md
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> some improvements on lab 5

docs/03_lab_monitor/0303.md, docs/03_lab_monitor/0304.md, docs/05_lab_openai/0501.md, docs/05_lab_openai/0502.md
as title
refine the process
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
=> mark some steps optional, and hide the steps to deploy existing AI

azure.yaml, infra/bicep/main.bicep
update name in automation configs
Currently the automation works for both old & new repo
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
=> change name to java-on-aca in automation config

cleanup.md, docs/02_lab_launch/0209.md, more.md, tips.md
* hide the page more.md
* refine the steps on cleanup and tips
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
=> refine cleanup and tips docs

Dockerfile, docs/02_lab_launch/0201.md, docs/02_lab_launch/0207.md, docs/02_lab_launch/0208.md
1. Add Dockerfile for github docer-compose
2. Hide some optional steps with `<detail>` & `<summary>`
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
=> use detail & summary to collapse some optional steps

docs/02_lab_launch/0201.md, docs/02_lab_launch/0202.md, docs/02_lab_launch/0203.md, docs/02_lab_launch/0206.md, docs/03_lab_openai/0301.md, docs/04_lab_monitor/0402.md, docs/04_lab_monitor/0403.md, docs/04_lab_monitor/0405.md, install.md, tools/create-azure-resource.sh
add more notes
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
=> more notes on the lab steps

docs/02_lab_launch/0201.md, docs/02_lab_launch/0202.md, docs/02_lab_launch/0203.md, docs/02_lab_launch/0206.md, docs/02_lab_launch/0209.md, docs/03_lab_openai/0301.md, docs/03_lab_openai/03_openai.md, docs/03_lab_openai/03_openai_existing.md, docs/04_lab_monitor/0402.md, docs/04_lab_monitor/0403.md, docs/04_lab_monitor/0405.md, index.md, install.md
* ...
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
Preview server updated here: https://ronline-java-aca-preview.azurewebsites.net/
=> Remaining train the trainer tasks

README.md
Added required H2 headers back into the readme.md file as required by the AI Gallery. Broke up existing readme contents to fill these sections, and added list of useful links in  the resources section.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
Review the Readme.md file in the working branch: https://github.com/Azure-Samples/java-on-aca/tree/Update-Readme.md-for-AI-Gallery-compliance
=> Update readme.md for AI gallery compliance

.devcontainer/postCreateCommand.sh, docs/04_lab_monitor/0403.md, tools/azure-resource.profile, tools/create-azure-resource.sh
fix and refinements on scripts
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
=> Some minor refine on the scripts
